# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bW0uzY9Xg0preRtHeodbyuLMwsf6JYM3
"""

import math

class BMIcalculator:
    def __init__(self):
        pass

    @staticmethod
    def get_user_input():
        """
        Get user input for name, weight, and height.
        """
        while True:
            name = input("What's your name? ").strip()
            if name:
                break
            else:
                print("Please enter a valid name.")

        while True:
            try:
                weight = float(input("Enter your weight in kilograms: "))
                height = float(input("Enter your height in inches: "))
                if weight <= 0 or height <= 0:
                    raise ValueError("Weight and height must be positive numbers.")
                break
            except ValueError as e:
                print("Invalid input. Please enter a valid number.")

        return name, weight, height

    @staticmethod
    def calculate_bmi(weight, height):
        """
        Calculate BMI (Body Mass Index) given weight in kilograms and height in inches.
        Formula: BMI = (weight / (height^2)) * 703 (as height is in inches)
        """
        bmi = (weight / (height ** 2)) * 703
        return bmi

    @staticmethod
    def interpret_bmi(bmi):
        """
        Interpret BMI and provide weight status.
        """
        if bmi < 18.5:
            return "Underweight"
        elif 18.5 <= bmi < 25:
            return "Normal weight"
        elif 25 <= bmi < 30:
            return "Overweight"
        else:
            return "Obese"

    @staticmethod
    def suggest_guidance(bmi):
        """
        Suggest guidance for overweight users.
        """
        if bmi >= 25:
            guidance = "You are in the overweight range. It's recommended to consult with a healthcare professional for guidance on a suitable diet and exercise plan."
        else:
            guidance = "You are within a healthy weight range. Keep up the good work!"
        return guidance

    def run(self):
        print("Welcome to the BMI Calculator")
        print("-----------------------------")
        name, weight, height = self.get_user_input()
        bmi = self.calculate_bmi(weight, height)
        print(f"Hello, {name}! Your BMI is: {bmi:.2f}")
        print("Weight status:", self.interpret_bmi(bmi))
        print(self.suggest_guidance(bmi))


if __name__ == "__main__":
    bmi_calculator = BMIcalculator()
    bmi_calculator.run()









